REPO_DIR_NAME = ".mygit"
HEAD_FILE_NAME = "HEAD"
CONFIG_FILE_NAME = "config"
OBJECTS_DIR_NAME = "objects"
OBJECTS_DIR_SUBDIRS = ["pack", "info"]
HEADS_DIR_NAME = "heads"
REFS_DIR_NAME = "refs"
DEFAULT_BRANCH_NAME = "main"